openfoodfacts/hunger-games

src/App.js
src/components/LogoForm.jsx
src/components/LogoGrid.jsx
src/components/QuestionFilter/useFilterSearch.js
src/pages/logos/LogoAnnotation.jsx
src/pages/logos/LogoUpdate.jsx
src/robotoff.js

Migrate logo game

---

src/components/LogoForm.jsx
src/components/LogoGrid.jsx
src/pages/logos/LogoAnnotation.jsx

Logos styling fixed

---

package.json
src/components/QuestionFilter/QuestionFilter.jsx
src/pages/insights/FilterInsights.jsx
src/pages/insights/InsightsGrid.jsx
src/pages/insights/index.jsx
src/robotoff.js
yarn.lock

- description of the PR
Add a filter that can interact with its parent to filter insights grid

[Insight] add filter for insight page

---

netlify.toml
src/App.js
src/components/LogoSearchForm.jsx
src/pages/logos/LogoSearch.jsx

go to the `logos/search/` to be able to search logos from a product barcode, or with a specific annotation

feat add logos/search url

---

package.json
src/App.js
src/components/QuestionCard.jsx
src/components/QuestionFilter/QuestionFilter.jsx
src/components/QuestionFilter/useFilterSearch.js
src/localeStorageManager.js
src/pages/home/index.jsx
src/pages/index.js
src/pages/questions/index.jsx
yarn.lock

Allows to save/unsave a filter state

feat: allows to save filters

---

.github/workflows/codeql-analysis.yml

ci: codeql

---

src/App.js
src/pages/index.js
src/pages/nutriscoreValidator/index.jsx
src/pages/questions/useQuestionBuffer.js

Use the same layout as logo annotation but to validate the nutriscore insights

feat: add a page to experiment with grid selection

---

src/App.js
src/components/QuestionFilter/QuestionFilter.jsx
src/components/ResponsiveAppBar.jsx
src/pages/questions/ProductInformation.jsx
src/pages/questions/QuestionDisplay.jsx
src/pages/questions/index.jsx
src/pages/settings/index.jsx

UI refacto

---

src/components/QuestionCard.jsx
src/localeStorageManager.js
src/pages/home/index.jsx

feat: Allows to edit favorite question cards

---

README.md

doc: light mode dark mode README

doc: light mode dark mode README

---

src/localeStorageManager.js
src/pages/questions/ProductInformation.jsx
src/pages/settings/index.jsx

- Hide images state now stored in the local storage as part of the settings
- #59

issue 59, store hide images state

---

.gitignore
src/components/ResponsiveAppBar.jsx
src/pages/questions/ProductInformation.jsx
src/pages/questions/QuestionDisplay.jsx

Aligned pictures in Product information and changed navBar

Fixed shortCut issue and added small UI improvements

---

src/i18n/common.json
src/i18n/en.json
src/pages/settings/index.jsx

- Added a link at the bottom of the settings page that directs to the issue github page
- Fix #57

added report an issue link in the settings page

---

src/components/ResponsiveAppBar.jsx

fix center button text in menu

---

.github/workflows/auto-assign-pr.yml

ci: auto assign pr

---

.github/workflows/release-please.yml

ci: Add release please

---

.github/workflows/github-projects-pr.yml
.github/workflows/github-projects.yml

- ci: Auto-add issues and PRs to GitHub Projects

ci: Auto-add issues and PRs to GitHub Projects

---

README.md

- added slack direction and channel

readme: added slack direction and channel

---

src/components/QuestionCard.jsx

Fix #120
Save filter title on Enter and cancel the edition on Escape

feat:  save on enter and cancel on escape

---

src/pages/nutriscoreValidator/index.jsx
src/pages/questions/useQuestionBuffer.js
src/robotoff.js

allows to crop nutriscore

---

package.json
src/App.js
src/index.js
yarn.lock

install Matomo

---

src/App.js
src/pages/index.js
src/pages/nutrition/index.jsx
src/pages/nutrition/productCard.jsx

I did split my PR to several small PRs. I added the page "nutrition" to the application and display product card with two buttons. Skip and validate.

Nutrition game product card display

---

.github/labeler.yml

- ci: Update automatic PR labeler

ci: Update automatic PR labeler

---

public/index.html

feat: Better page description

---

src/pages/nutriscoreValidator/index.jsx

Fix #166
Added:
- select all unselect all buttons
- if shift+click the range between last click and new click take the same selection state as the previously clicked
- shift + rigth/left arrow add the lastclicked image + the left/right one

feat: Add shortcut for nutriscore selection

---

src/App.js
src/index.tsx
src/pages/flaggedImages/index.jsx
src/pages/index.js
src/pages/nutriscoreValidator/index.jsx

Add a small page: `/flagged-images` that list all the images reported by users in hunger game

feat: Visualized flagged images

---

src/externalApi.js
src/pages/logos/LogoUpdate.jsx
src/pages/questions/ProductInformation.jsx

feat: Allow flagging logo in edit page

---

src/App.js

It shows 404 if not logged in with an admin username
We discussed allowing users to see the page but not act. It sounds like a bad idea, because if user can not edit it, why should they see it

404 flagged images

---

src/components/ResponsiveAppBar.jsx
src/pages/home/index.jsx
src/pages/questions/UserData.tsx

Fix #177
Part of #102
- If user is logged in the "Want to make your contribution count? Create an account or sign in on Open Food Facts!" section is removed from the home page
- If user is not logged in clicking on the icon check if the cooky as been updated, if not, it open login page
- If user answer 5 questions and is not logged in a dialog open encouraging to do so

feat: remove the incitation to login when it's the case

---

src/pages/home/UserData.jsx
src/pages/home/index.jsx

feat: Show user statistics

---

src/App.js

I realized we had infinite looping in rendering. After trial and errors, seems to come from this `useEffect`

fix: infinite refresh loop

---

src/pages/logos/LogoAnnotation.jsx

fix: send logo annotations to robotoff

---

src/components/Opportunities.tsx
src/pages/home/index.jsx
src/robotoff.ts

feat: Show top insight in the home page

---

src/pages/eco-score/index.jsx

Fix: Replace "en" by "fr" for AB insight

---

src/pages/logos/LogoUpdate.jsx

`logoId` was not fetched because it's given in the URL parameters. But I forget to pass its value to the form

Fix: Updating  logo annotation

---

src/components/QuestionFilter/QuestionFilter.jsx
src/components/ResponsiveAppBar.jsx
src/pages/questions/QuestionDisplay.jsx
src/pages/questions/index.jsx

- Display filter editing in a model to be mobile friendly
- Increase skip button height (was hard to press for my big fingers)
- Remove zooming on main image which is pretty bad about CSS
- Improve full width on small screen

feat: UI improvement of question game

---

src/components/QuestionFilter/LabelFilter.tsx

Fix #223 and prevent fetching autocomplete suggestion when there is nothing to complete

fix: error when cleaning autcomplete labels

---

src/pages/questions/ProductInformation.jsx

Fix #171
@teolemon This adds in dev mode the following interface:
To answer you need 2 clicks, such that you can revert a wrong click if needed

feat: show other questions in dev mode

---

src/pages/questions/DebugQuestion.tsx

feat: support additional API request for logo preview in debug mode

---

src/components/QuestionFilter/LabelFilter.tsx

In https://hunger.openfoodfacts.org/logos/search/ start searching for a logo, clean your search and write the same thing again, first character will be deleted
This should fix he problem

fix: prevent resetting autocomplet value when no result found

---

src/components/QuestionFilter/const.js
src/components/QuestionFilter/useFilterSearch.js
src/pages/questions/QuestionDisplay.jsx

Small improvements
Fix #242
Fix #244

Fix missing value in weight questions and sort by popularity by default

---

src/components/BackToTop.tsx
src/pages/logos/LogoAnnotation.jsx

The form stays sticky to the top
And add a small button at the bottom right to scroll top

User feedbacks: Allows to keep an eye on the form in logos game

---

src/pages/logos/LogoAnnotation.jsx
src/pages/nutriscoreValidator/index.jsx

I extended the logo game to answer other questions (EU organic and AB logos)

Make nutriscore game to more generic (other logos)

---

src/i18n/common.json
src/i18n/en.json
src/pages/eco-score/index.jsx

feat: describe eco-score page

---

src/i18n/messages.js

- feat: add Japanese selection in options since we now have translations

feat: add Japanese selection in options

---

README.md

- ci: few additions to the README

ci: few additions to the README

---

src/pages/logos/LogoAnnotation.jsx

Fix: Force logo game to show the requested logo with distance 0

---

src/robotoff.ts

Fix #295
After reading axios types: it's `axios.post(URL, data, config)`

Fix: move withCredentials from data to config

---

src/components/Opportunities.tsx
src/components/SmallQuestionCard.jsx
src/const.js
src/off.js
src/pages/eco-score/index.jsx
src/robotoff.ts

Feat: Improve agri-balise categories cards

---

.github/workflows/label.yml

- ci: missing file for autolabeler for PRs

ci: missing file for autolabeler for PRs

---

.github/CODEOWNERS

ci: add codeowners file

---

.github/workflows/merge-conflict-autolabel.yml

- ci: merge conflict autolabel

ci: merge conflict autolabel

---

.github/workflows/dependency-review.yml

ci: dependancy review

---

src/robotoff.ts

use taxonomy_value in logo search

---

src/i18n/common.json

fix: small string fixes

---

src/App.js
src/contexts/colorMode.jsx
src/index.tsx
src/localeStorageManager.ts
src/pages/settings/index.jsx

Introduce dark mode

---

src/components/LogoGrid.jsx
src/pages/questions/ProductInformation.jsx

Fix product information and dark mode

Fix small bugs

---

package.json
src/components/CroppedLogo.tsx
src/components/QuestionFilter/QuestionFilter.jsx
src/components/ZoomableImage.tsx
src/components/welcome/Welcome.jsx
src/i18n/common.json
src/i18n/en.json
src/pages/nutrition/productCard.jsx
src/pages/questions/ProductInformation.jsx
src/pages/questions/QuestionDisplay.jsx
src/pages/questions/index.jsx
src/pages/questions/utils.ts
yarn.lock

[netlify preview](https://deploy-preview-358--warm-cannoli-79bbb2.netlify.app/)
----
Fix #346
Part of #302
Fix #261
Fix #278
Fix #243
---
<table>
<tr>
<td> Before
<td> After
<tr>
<td><img src='https://user-images.githubusercontent.com/45398769/201492573-af58e1b8-cc2d-4233-bbf2-9ac6ff0bcf60.png'/>
<td><img src='https://user-images.githubusercontent.com/45398769/201492579-0ebe773e-d4b4-49fd-9f66-82a6213d85be.png'/>
</table>

UX iteration on question game

---

src/pages/questions/ProductInformation.jsx
src/pages/questions/QuestionDisplay.jsx
src/pages/questions/index.jsx
src/pages/questions/useQuestionBuffer.ts

When user skip a quesiton, send the skip to the server

feat: Send skip to server

---

src/pages/logosValidator/LogoQuestionValidator.jsx

fix: typo fixes

---

src/App.js
src/components/ResponsiveAppBar.jsx

Changed header color to harmonize it with new Open Food Facts design
Fixes #273

fix: change header color to match new OFF design

---

src/pages/logosValidator/LogoQuestionValidator.jsx
src/pages/questions/useQuestionBuffer.ts
src/robotoff.ts

No more NO LOGO cards thanks to tips an triks provided in https://github.com/openfoodfacts/robotoff/issues/1012#issuecomment-1346351704

feat: use predictor in INAO game

---

src/pages/logosValidator/LogoQuestionValidator.jsx

reduce number of images in one page

---

src/components/LogoForm.jsx
src/components/LogoGrid.jsx
src/pages/home/UserData.jsx
src/pages/logos/LogoSearch.jsx

Allows inline logo editing

---

README.md

docs: readme-refactor

---

src/pages/shouldLoggedinPage/index.js

- fix: typo reported by Thomas

fix: typo reported by Thomas

---

README.md

- docs: document how to edit dashboards

docs: document how to edit dashboards

---

README.md

docs: quickstart

---

src/pages/logosValidator/DashboardCard.tsx
src/pages/logosValidator/LogoQuestionValidator.jsx
src/pages/logosValidator/dashboardDefinition.ts

Part of #456 
I tried to implement the steps as mentioned in the comment section of the issue #456 .

Fix: Recycling dashboard links to labels vs packaging

---

src/components/LogoForm.jsx
src/components/LogoSearchForm.jsx
src/i18n/common.json
src/i18n/en.json
src/pages/logos/LogoDeepSearch.jsx
src/pages/logos/LogoSearch.jsx
src/robotoff.ts

Allows to enter no_log, and randomize the logos used to initialize the deep search game

Feat: Small logo improvements

---

src/components/AnnotateLogoModal.tsx
src/components/QuestionFilter/LabelFilter.tsx
src/pages/logos/LogoAnnotation.jsx
src/pages/logos/LogoDeepSearch.jsx
src/pages/logos/ProductLogoAnnotations.jsx

Use a modal to allow deselect logos before sending the request
Fix #461
Fix #460

Feat: For all logo game, move annotation step in a popup

---

src/components/AnnotateLogoModal.tsx
src/components/QuestionFilter/LabelFilter.tsx
src/pages/logos/LogoAnnotation.jsx
src/pages/logos/LogoDeepSearch.jsx
src/pages/logos/ProductLogoAnnotations.jsx

Use a modal to allow deselect logos before sending the request
Fix #461
Fix #460

new logo UX

---

src/components/AnnotateLogoModal.tsx
src/pages/logos/LogoDeepSearch.jsx

Fixes of logo games regressions

---

src/components/ResponsiveAppBar.jsx

fix: allows scoll on mobile (a hidden modal was taking the focus)

---

src/components/QuestionFilter/LabelFilter.tsx

If the value is not taken from the taxonomy it add a warning:
Otherwise it just show the associated tag
The `blur` event listener was buggy. Now it should not be necessary anymore to press enter. leaving the field is enought to update the value

Fix: Autocomplete behavior

---

src/pages/logos/LogoAnnotation.jsx

- Select all button was selecting logo cards even though its annotated already
- #462 
- #37

fix: select all in logo game

---

src/pages/logosValidator/dashboardDefinition.ts

fix: logo-fixes

---

src/pages/logosValidator/dashboardDefinition.ts

- fix: fixes-to-logo-dashboard

fix: fixes-to-logo-dashboard

---

src/components/LogoSearchForm.jsx
src/i18n/common.json
src/i18n/en.json
src/pages/logos/LogoDeepSearch.jsx
src/pages/logos/ProductLogoAnnotations.jsx
src/pages/logosValidator/LogoQuestionValidator.jsx

Redirect logos games to other ones

---

src/i18n/common.json

fix: wording fixes

---

src/pages/packaging/Row.tsx
src/pages/packaging/index.tsx
src/pages/packaging/useBuffer.ts

fix the download of number of items
fix the data fetching when using URL such as https://hunger.openfoodfacts.org/packaging?code=3609060004620

Fix packaging interface

---

src/pages/logosValidator/LogoQuestionValidator.jsx

fix: mass logo annotation

---

src/i18n/en.json

small typo

---

src/components/AnnotateLogoModal.tsx
src/hooks/matomoEvents.ts
src/pages/logos/LogoAnnotation.jsx
src/pages/logos/LogoDeepSearch.jsx
src/pages/logos/ProductLogoAnnotations.jsx
src/pages/questions/QuestionDisplay.jsx

Track answers in matomo

---

src/i18n/common.json

- fix: Fix a few typos in common.json that were fixed in en.json

fix: Fix a few typos in common.json that were fixed in en.json

---

.husky/pre-commit

We should use only a package manager, so let's use yarn even for pre-commit checks!

Make husky pre-commit use yarn

---

public/robots.txt

The current file is invalid, webpage is still indexed by Google.

fix: fix robots.txt

---

src/pages/logos/LogoDeepSearch.jsx

Pressing remove will remove selected logos from the list. No request is sent to the server

feat: Allow to remove some logos from deep search

---

src/pages/logosValidator/dashboardDefinition.ts

feat: dashboard additions

---

src/pages/questions/QuestionDisplay.jsx
src/pages/questions/QuestionFilter.jsx
src/pages/questions/store.js

fix: Add all countries in the question filter

---

src/pages/eco-score/index.tsx

- fix: fix broken logos and move to static.off.org

fix: fix broken logos and move to static.off.org

---

src/pages/logosValidator/dashboardDefinition.ts

- fix: move hardcoded dashboard to static

fix: move hardcoded dashboard to static

---

src/i18n/common.json
src/i18n/en.json
src/off.ts
src/pages/insights/InsightsGrid.jsx
src/pages/questions/ProductInformation.jsx

- feat: add shortcut to crop from question game

feat: add shortcut to crop from question game

---

src/App.jsx
src/pages/bug/index.tsx

bug: Reproduce the ingredient update error

---

src/pages/bug/index.tsx

Experiemnt

---

package.json
src/off.ts
src/pages/ingredients/IngeredientDisplay.tsx
src/pages/ingredients/index.tsx
src/pages/ingredients/useData.tsx
yarn.lock

- Fix sending data (still need to test)
- Allow to zoom in full resolution image
- show user and date of image upload

Improve ingredients

---

src/pages/eco-score/index.tsx
src/pages/ingredients/index.tsx
src/pages/ingredients/useData.tsx
src/pages/settings/index.jsx

Allows ingredients game to filter products by country

---

src/pages/eco-score/index.tsx
src/pages/ingredients/index.tsx
src/utils/getCountryId.ts

feat: Support 2 letters code four countries

---

src/components/TaxonomyAutoSelect.tsx

feat: Use the name and not the id for brand

---

.github/labeler.yml

- fix: labeler.yml with new syntax

fix: labeler.yml with new syntax

---

src/components/QuestionFilter/LabelFilter.tsx
src/const.ts
src/pages/not-found/index.jsx

fix origine link

---

src/components/CroppedLogo.tsx
src/pages/logosValidator/LogoQuestionValidator.jsx
src/pages/questions/DebugQuestion.tsx

Fix #807
Seems there is some duplicated code, but will not fix that in this PR

Stop using `logo.data.bounding_box` from insight API

---

src/App.jsx
src/components/TaxonomyAutoSelect.tsx
src/offTaxonomy.ts
src/pages/taxonomyWalk/Error.tsx
src/pages/taxonomyWalk/ItemCard.tsx
src/pages/taxonomyWalk/index.tsx

Play with some taxonomy explorer

---

src/pages/nutrition/utils.ts

Fix request to robotoff

---

src/pages/questions/QuestionFilter.tsx

set width to 150 for big screens

---

src/pages/nutrition/PictureSection.tsx

Show if image is selected as a nutriment image

---

src/pages/nutrition/index.tsx
src/pages/nutrition/utils.ts

fix: Avoid duplicated nutriments

---

README.md

docs: README refresh

---

src/components/Footer/DownloadOpenFoodFacts.jsx

- add UTMs
- Deprecated Windows Store
- Unhardcode APK

fix: fixes for footer - Update DownloadOpenFoodFacts.jsx

---

.husky/pre-commit
README.md
package.json
src/App.jsx
src/components/LogoGrid.jsx
src/components/QuestionCard.jsx
src/components/QuestionFilter/LabelFilter.tsx
src/components/SmallQuestionCard.jsx
src/contexts/CountryProvider/CountryProvider.tsx
src/hooks/useSearchParamsState.ts
src/pages/logosValidator/DashboardCard.tsx
src/pages/nutrition/NutrimentCell.tsx
src/pages/nutrition/index.tsx
src/pages/nutrition/useNutrimentTranslations.ts
src/pages/nutrition/useRobotoffPredictions.ts
src/pages/nutrition/utils.ts
update-countries.js
yarn.lock

Bump: Update dev libraries

---

package.json
src/App.jsx
src/components/OffWebcomponents.tsx
src/components/ResponsiveAppBar.jsx
src/i18n/common.json
src/i18n/en.json
src/pages/ingredient-detection/index.jsx
src/pages/ingredient-spellcheck/index.jsx
src/pages/nutrition/index.tsx
src/types/off-webcomponents.d.ts
yarn.lock

- Add robotoff-ingredient-detection
- Rename webcomponent to new name
- https://github.com/orgs/openfoodfacts/projects/140/views/1?pane=issue&itemId=113842146&issue=openfoodfacts%7Copenfoodfacts-webcomponents%7C155

feat: up webcomponent to 1.7.0 to add robotoff-ingredient-detection

---

package.json
yarn.lock

- fix: update off wc to fix lang problem

fix: update off wc to fix lang problem

---

src/components/ResponsiveAppBar.jsx

Core of this issue is that Menu.open depends on anchorEl.
I found that, even if "Menu.open" = false ; the Menu doesn't closes.
So, I am proposing to do manual conditional rendering of "Menu" component with the Menu.open attribute provided from MUI.
This simple fix is solving the issue.
https://github.com/user-attachments/assets/e1d33eb6-7587-4d10-b11b-52c2d744a5a0
- #1176

Fixed: Menu not closing

---

src/components/ResponsiveAppBar.jsx
src/i18n/en.json

I had merged the two ingredient games "ingredient-spellcheck" and "ingredient-detection" into one MenuItem.
Look at screenshots for clearer picture.
https://github.com/user-attachments/assets/a759715c-158e-4db1-bae0-03581f73aa1d
- #1199

Task Done : merged two ingredients game into one menuitem

---

README.md

- docs: Update README.md with CORS issues

docs: Update README.md with CORS issues

---

src/i18n/en.json

- fix: Small rename of menus before a more thorough rework (en.json)

fix: Small rename of menus before a more thorough rework (en.json)

---

package.json
yarn.lock

ci: webcomponent-bump
