openfoodfacts/hunger-games

src/pages/questions/ProductInformation.jsx, src/pages/questions/index.jsx
When we display the question of index 0 in the buffer, we also ask the browser to fetch images with indexes 1, 2, 3, 4
such that time between two question display is reduced
=> anticipate image download for next questions

src/i18n/common.json, src/pages/questions/UserData.jsx
- In the Questions page, rephrased 'Remaining' to 'Remainin questions'
- Replaced a hardcoded string 'Remaining' with a translation string
- [#37](https://github.com/openfoodfacts/hunger-games/issues/37) 
- [What can I work on?](https://github.com/openfoodfacts/smooth-app/issues/1)
...  Remaining >> Remaining questions
=> fix: questions page, rephrase remaining annotations

.github/workflows/codeql-analysis.yml, README.md, package.json, yarn.lock
Realised that I installed prettier locally, 
the idea is to force thanks to a command line `yarn prettier --write .` the format of all the code.
This should avoid PR containing useless line modifications such as a space added at the end of a line of code, `'` replaced by `"`, ...
=> code: add prettier to the dependencies

src/components/ResponsiveAppBar.jsx
When clicking on "Hunger Games" in the header you stay in the same page instead of going to the home page
Now you  go to the home page
=> fix: link to home page use react-router

src/App.js, src/components/ResponsiveAppBar.jsx, src/contexts/devMode.jsx, src/localeStorageManager.js, src/pages/settings/index.jsx
https://user-images.githubusercontent.com/63084088/183458111-d221145f-1a10-4a40-80d5-65bb32020680.mov
Closes #131
=> feat: feature flags added to dev mode

src/components/ResponsiveAppBar.jsx, src/pages/questions/ProductInformation.jsx, src/utils.js
https://user-images.githubusercontent.com/63084088/184530483-b4beadb6-e1d3-42d3-a94e-83b6a87149ba.mov
Closes #22
=> feat: reporting images added

src/components/LogoForm.jsx, src/pages/logos/LogoAnnotation.jsx
Fix #140
Fix #137
- When sending the annotation, button shows a loading animation
- After annotation is sent to the server, the selected logos are unselected
- new button action
- select all
- unselect all
- refresh
- when the URL has the `logo_id` search parameter, the corresponding logo is always focused, and the value/type is filled with its value if already annotated
When the `logo_id` is set, refresh should lead to a new page, because refreshing with same search params leads to the same page
=> feat: logo game improvement

src/App.js, src/components/ResponsiveAppBar.jsx, src/components/welcome/Welcome.jsx
Add logged in information on desktop
Remove matomo on dev env (Fix #161)
=> show logged in status in app bar on desktop

src/components/LogoGrid.jsx
Fix #139 and some lines of #85
add a check box with same behavior as clicking on the image
remove the text from the action area: clicking on it do nothing, and so you can copy past labeled cards
=> feat: selectable logo annotation and add checkbox

src/i18n/common.json, src/i18n/en.json, src/pages/home/UserData.jsx
Fix #204 by allowing trnslations
=> feat: Improve statistic descriptions

src/components/LogoForm.jsx, src/components/LogoSearchForm.jsx, src/components/QuestionFilter/LabelFilter.tsx, src/pages/logos/LogoAnnotation.jsx, src/pages/logos/LogoSearch.jsx
For logo search/annotation I display the key below (not only the translation, assuming users know how to works)
Fix #175 
To the far right, I added a link to the search interface
=> feat: improve logos UI

src/contexts/devMode.jsx, src/localeStorageManager.ts, src/pages/nutriscoreValidator/index.jsx, src/pages/questions/DebugQuestion.tsx, src/pages/questions/ProductInformation.jsx
Fix #221
Mostly for usage on desktop. It adds two elements:
- The first one is a resume with the basic information you wanted. I put the 3 requested information, plus a crop of the logo.
- The second one is simply a print of the insight as a JSON
=> feat: Show debug informations about insights

src/robotoff.ts
- Fixes Insights service call for non-annotated search. The annotation parameter is not sent when the annotation is "non-annotated".
- Fix #230 
- #230
=> Fix insights service call for non-annotated search

src/components/QuestionCard.jsx, src/pages/questions/QuestionDisplay.jsx, src/pages/questions/useQuestionBuffer.ts, src/robotoff.ts
When clicking on the link for a given value, it should not remove the filter parameters already set
For example when clicking on fruit juice:
- currently: `country: France` become `type: category, value: fruit juice`
- now: `country: France` become `country: France, type: category, value: fruit juice`
=> fix: keep already set filter parameters

src/components/Opportunities.tsx
used translated value for url generation (of course it's a bad idea)
=> Fix: Opportunities broken links

src/hooks/matomoEvents.ts, src/pages/questions/useQuestionBuffer.ts
The goal of hunger games is to annotate products. To know if we are doing good, we need to know how many products get annotated by users.
In this PR we send a matomo action each time a user is answering a question
=> matomo: Track answered questions

src/App.js, src/pages/index.js, src/pages/logosValidator/LogoQuestionValidator.jsx, src/pages/logosValidator/index.jsx, src/pages/questions/useQuestionBuffer.ts
Sounds like AOP/AOC logos ned some cleaning, So I created a similar annotator than the one for nutriscore logo detection
The only problem is that AOC and AOP questions can also be generated from OCR, then I don't have image to display. Then after some time the user has to refresh the page to get new bath of logos
=> feat: Split interface for fast nutriscore answer and INAO logos

src/pages/logosValidator/LogoQuestionValidator.jsx
I first thought it would be nice to do not display cards when their is no cropped logo associated. But it's a mistake because internaly, the <kbd>Shift</kbd>+click will select those questions without letting the user realise what they are doing.
=> Fix: Show question without logo to avoid false annotation

src/pages/logos/LogoSearch.jsx, src/pages/packaging/index.tsx, src/pages/packaging/useBuffer.ts, src/pages/settings/index.jsx
Fix #396 by allowing to pass parameter code in the URL
hunger.openfoodfacts.org/packaging?code=3245414079106
Also adding `country` and `creator` parameters
+ some minor fixes
=> feat: allows to see packaging interface for specific products

src/pages/logos/LogoAnnotation.jsx, src/robotoff.ts
- Changed route for ANN search
- The robotoff ANN search now returns the query logo id in a field "query_logo_id". Added this id to the results of ANN search, replacing the work done in #294.
- Should wait the deployment of the new ANN search in Robotoff (expected for the 26th of december).
=> fix: Adapt Hunger Games to the ANN modification in Robotoff

src/i18n/common.json, src/i18n/en.json, src/pages/questions/QuestionDisplay.jsx
Fix #496
- before it was showing only loading text, now it shows loading circular animation
- #496
=> feat: add loading animation before question display

src/components/QuestionFilter/QuestionFilter.jsx, src/pages/eco-score/index.jsx, src/pages/questions/ProductInformation.jsx, src/utils.js
- Capitalise country name while showing
#
- 
- #37
=> fix: capitalise country name.

src/components/QuestionFilter/useFilterSearch.js, src/hooks/useUrlParams.js, src/pages/insights/index.jsx, src/pages/logos/LogoAnnotation.jsx, src/pages/logos/LogoDeepSearch.jsx, src/pages/logos/LogoSearch.jsx, src/pages/logos/ProductLogoAnnotations.jsx, src/pages/logosValidator/LogoQuestionValidator.jsx, src/pages/packaging/index.tsx
Solves https://github.com/openfoodfacts/facets-knowledge-panels/issues/80
@sumit-158 You can now (after PR merge of course 😉) use `value_tag` in all urls. Is there other parameters that are problematic?
=> Add synonyms to `useUrlParams`

src/components/LogoSearchForm.jsx, src/components/QuestionFilter/LabelFilter.tsx
In the ternary operator, i added two && checks that will be true only for non empty string and not null.  This fixed the issue but caused the label filter to lose focus once the user types in a letter. So,additionally, I added a useEffect and useRef hook.  The useEffect hook re-runs everytime the innerValue changes. The useRef hook holds on to the value that the user types and re-focuses on the label filter, this runs everytime the useEffect hook runs.
Fix #480
=> Fix: fixed warn on empty values

src/App.js, src/components/Opportunities.tsx, src/pages/eco-score/index.jsx, src/pages/flaggedImages/index.jsx, src/pages/home/index.jsx, src/pages/insights/index.jsx, src/pages/logos/LogoAnnotation.jsx, src/pages/logos/LogoDeepSearch.jsx, src/pages/logos/LogoUpdate.jsx, src/pages/logos/ProductLogoAnnotations.jsx, src/pages/logosValidator/DashBoard.tsx, src/pages/logosValidator/LogoQuestionValidator.jsx, src/pages/not-found/index.jsx, src/pages/nutrition/index.jsx, src/pages/packaging/index.tsx, src/pages/questions/index.jsx, src/pages/settings/index.jsx, src/pages/shouldLoggedinPage/index.js
- imported routes from lazy imports
- added suspense wrapper around all pages
- since there are many routes in the app, we can delay js bundle file downloads by adding lazy imports
- Without lazy import
- With lazy import
=> feat: Add lazy import for different routes

src/App.jsx, src/components/Opportunities.tsx, src/pages/eco-score/index.jsx, src/pages/home/index.jsx, src/pages/insights/index.jsx, src/pages/loader/index.jsx, src/pages/logos/LogoDeepSearch.jsx, src/pages/logos/LogoUpdate.jsx, src/pages/logos/ProductLogoAnnotations.jsx, src/pages/logosValidator/LogoQuestionValidator.jsx, src/pages/packaging/index.tsx, src/pages/questions/QuestionDisplay.jsx, src/pages/questions/index.jsx, src/pages/settings/index.jsx
Created Loader Component and added it in all the pages
#668
=> aligned loader center while loading pages

package.json, yarn.lock
As we're now using Vite, we don't need that dependency.
=> chore: remove react-scripts dependency

.github/workflows/deploy.yml, deploy.sh
- In #663 I forgot to modify the `build.sh` script. This fixes it.
- Now we're directly pushing to GitHub Pages with an action, instead of pushing to the branch.
=> Fix GitHub pages deploy

.github/workflows/deploy.yml
@alexfauquette apparently I forgot to add this to the last PR #666
=> fix: add permissions to GH_TOKEN for Pages deployment

src/pages/logos/LogoAnnotation.jsx, src/pages/logos/LogoDeepSearch.jsx
Fix slack message
Two related issues with logo annotation:
1. Selecting a range of logos will toggle any logos in the range, regardless of whether or not they already have a value. Since the button is disabled if they have an annotation, they can't be deselected by clicking on them.
**Cause**: Whether or not the logo has an annotation is not checked at this line: https://github.com/openfoodfacts/hunger-games/blob/31327c2d392b7874755482d0663e15aea0b27789/src/pages/logos/LogoAnnotation.jsx#L192
**Solution**: Add `&& logo.annotation_type === null && logo.annotation_value === null`
2. "Select all" have a similar issue, this time only if the annotation type has an empty value.
**Cause**: Only whether or not there is a value is checked at this line: …
=> fix: Do not select logos with a value

.github/workflows/deploy.yml, package.json, src/components/QuestionFilter/useFilterSearch.js, src/components/welcome/Welcome.jsx, src/pages/loader/index.jsx, yarn.lock
Fixes per commit:
- Impossible to switch pages in the tour (app crashes). The reason being the asset import not supported by viteJs
- pretty-quick does not support prettier v3. So I downgrade prettier to v2 otherwise husky prevent me from commiting(the [GitHub issue](https://github.com/azz/pretty-quick/issues/164#issuecomment-1625533955))
- The loader background was hardcoded with a dark color, leading to a black spinner on a black background in light mode. Here is the before after 🙈
=> few bug fixes

src/components/welcome/Welcome.jsx, src/pages/packaging/useBuffer.ts, src/pages/questions/QuestionFilter.jsx, src/pages/questions/store.js
If no questions have associated images, the loading was stuck into waiting state do to a wrong selector.
The next page to fetch was accurately computed, but the selector was looking at the wrong property (bad copy past)
Also fix the checkbox "sort by popularity" which was always unselected
=> fix question fetching

src/const.ts, src/pages/questions/utils.ts
images.openfoodfacts.org is the domain to use to serve images: it's hosted by a distinct server dedicated to serving images.
=> fix: update OFF_IMAGE_URL

src/components/LogoForm.jsx
- Prevents the reading properties on null error using optional chaining
- ToLowerCase function execution will be prevented when value of 'value' is equal to null.
- fix: #688
=> Fix : Blank screen problem

.prettierignore, src/App.jsx, src/pages/logosValidator/DashBoard.tsx, src/pages/logosValidator/dashboardDefinition.ts
- The deeplink system is marked as "to deprecate in 2024"
- any reason ?
- feat: adding deeplinks to logo dashboards
=> feat: adding deeplinks to logo dashboards

src/components/QuestionFilter/useFavorite.ts, src/hooks/useUrlParams.js, src/pages/questions/QuestionFilter.tsx, src/pages/questions/useFilterSearch.tsx
I'm moving to the use of `useSearchParams` to manage the filter state.
We have two states: the redux one that manages the robotoff queries, and the url one.
The redux stats is updated when search param is modified and the filter pop-up is not open. Which correspond to:
- a chip is removed
- The page update (first loading, or click on the value button)
I'm starting a general effort to move to TS to spot as much bugs as possible
=> Move question filter to TS and  store filter state directly in th url

src/pages/eco-score/index.tsx
Added deeplinking in eco-score page.
Used `useSearchParams` to navigate to specific **country** param.
#879
=> feat: deeplinking in eco-score page by country

src/localeStorageManager.ts, src/pages/eco-score/index.tsx, src/pages/settings/index.jsx
…in eco-score
Add country drop-down in settings page using `countries.json`.
Settings it as default in `eco-score` page.
Fix #887
=> feat: add country list in settings page, using it as default country in eco-score

src/pages/ingredients/ImageAnnotation.tsx, src/pages/ingredients/IngeredientDisplay.tsx, src/pages/ingredients/index.tsx, src/pages/ingredients/useData.tsx
=> Fix ingredients game paper cuts

src/components/LogoSearchForm.jsx, src/components/TaxonomyAutoSelect.tsx, src/const.ts, src/offSearch.ts, src/robotoff.ts
Fix #425
If the autocomplete works well and supports other locales, we could easily replace the hacky solution for labels and categories
=> feat: Use search a lisious for brand

.github/labeler.yml, src/pages/ingredients/index.tsx, src/robotoff.ts
Fix #1001
Use an intermediate function to convert id (en:France) to code (FR)
~@raphael0202 is it case-sensitive?~
After trying, it is 🙈 so I lowercased everything
For example, 
https://deploy-preview-1002--warm-cannoli-79bbb2.netlify.app/questions?country=en%3Aaustria
is calling
https://robotoff.openfoodfacts.org/api/v1/questions/?countries=at&order_by=popularity&lang=en&count=25&page=1
=> Fix robotoff API call for countries

src/const.ts
We shouldn't use static.openfoodfacts.org anymore, all images should use images.openfoodfacts.org (they're routed to another server that serves only images).
=> fix: use images.openfoodfacts.org to serve images

src/off.ts, src/pages/questions/ProductInformation.jsx, src/pages/questions/utils.ts
=> translate fields in products addition info

src/pages/nutrition/NutrimentCell.tsx, src/pages/nutrition/index.tsx, src/pages/nutrition/useRobotoffPredicitions.ts, src/pages/nutrition/utils.ts, vite.config.js
=> Show data from OFF

src/assets/countries.json, src/components/ResponsiveAppBar.jsx, src/contexts/CountryProvider/CountryProvider.tsx, src/pages/nutrition/NutrimentCell.tsx, src/pages/nutrition/index.tsx, update-countries.js
=> fix: make world an empty country code

src/pages/nutrition/Instructions.tsx, src/pages/nutrition/NutrimentCell.tsx, src/pages/nutrition/config.ts, src/pages/nutrition/index.tsx, src/pages/nutrition/utils.ts
Part of #1098
Still have to do the management of other nutritional pictures
@teolemon Could you review the instructions texts. I might have typo and some unclear explainations
=> Refine nutri game: limit nutriments to known list and add color

src/components/Footer/DownloadOpenFoodFacts.jsx, src/contexts/CountryProvider/CountryProvider.tsx, src/pages/ingredients/IngeredientDisplay.tsx
It seems that the `setSearchParams` is not like React setters. It needs to be in the dependencies of the callback. Otherwise it will update the serachParams of the first url
=> fix: Prevent global country update to go back to home page

src/hooks/useSearchParamsState.ts, src/i18n/common.json, src/i18n/en.json, src/pages/nutrition/NutrimentCell.tsx, src/pages/nutrition/index.tsx, src/pages/nutrition/useRobotoffPredictions.ts
=> Refacto search params management

src/vite-env.d.ts
TypeScript, by default, does not recognize static asset imports as valid modules. To fix this, we need to include include vite/client.
=> chore: add Vite client types reference file

src/components/ResponsiveAppBar.tsx, src/contexts/login.tsx, src/palette.d.ts, src/reportWebVitals.ts
Also makes the navbar assume the "mobile" setting when below the "lg" breakpoint, because links are overlapping otherwise.
=> chore: remove any from reportWebVitals, migrate ResponsiveAppBar to TS
